"""empty message

Revision ID: 414a9851358a
Revises: 6b6c7781401c
Create Date: 2020-05-03 11:37:14.341669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414a9851358a'
down_revision = '6b6c7781401c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! 
    # Running the below code alone ( which was auto generated ),
    # op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False)),
    # on running updrage command ( #4thThing in app.py ),
    # showed an error
    # sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "completed" contains null values
    # This meand we need to do some modification in this upgrade() method so that all the previous records gets
    # some default value
    # ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # Below codes are added to prevent the 
    # sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "completed" contains null values

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL')
    op.alter_column('todos','completed', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
