"""empty message

Revision ID: 67fc2ff11df8
Revises: a196a2dce948
Create Date: 2020-05-03 22:47:16.756129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fc2ff11df8'
down_revision = 'a196a2dce948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todolist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'todolists', ['todolist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todolist_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
